### ISSUE TITLE
MPM ?

### ISSUE THREAD

**Issue by anselal** [talkpython/responder-webframework-minicourse#1]
Did yo mean NPM at 
https://github.com/talkpython/responder-webframework-minicourse/blob/912c835dd2fdb692b8c4d67632225a35e949ea20/transcirpts/03-vuejs/2-vue-tour_transcript_final.txt#L35

**Comment by mikeckennedy** [comment]
Yes, I did, thanks for catching this. Will take a bit to find it's way to the player transcripts with caching and all, but it'll get there.

**Comment by anselal** [comment]
Thank you
